### ISSUE TITLE
Bot won't run

### ISSUE THREAD

**Issue by Isokok** [kiwijuice56/discord-log-bot#1]
When I run the script through Notepad ++, I can see a quick flash of new window loading, but the bot doesn't come online. When I use "node ." to run it I get this error,

Error: Cannot find module 'C:\Users\USER\Desktop\discord-log-bot-main'
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

What do I need to do to fix this?
Thanks.

**Comment by kiwijuice56** [comment]
Hi, how are you trying to run the script? This error looks notepad++ is attempting to interpret the code as javascript, but I am unsure. You can run the script by installing the most recent [Python interpreter](https://www.python.org/downloads/).

**Comment by Isokok** [comment]
> Hi, how are you trying to run the script? This error looks notepad++ is attempting to interpret the code as javascript, but I am unsure. You can run the script by installing the most recent [Python interpreter](https://www.python.org/downloads/).

The error shows when I use "node ." in the command prompt (in the right directory), no error, when using notepad ++, is shown it just doesn't run. Running using python doesn't work either, shows a flash of a command prompt like window but never runs.

**Comment by kiwijuice56** [comment]
Could you detail how you ran the script with python? Try using the terminal to navigate to the directory with the script and using the python command to run it.

**Comment by Isokok** [comment]
> Could you detail how you ran the script with python? Try using the terminal to navigate to the directory with the script and using the python command to run it.

Ok, so while running it with the py command still didn't work it defiantly narrowed down the issue.

> Traceback (most recent call last):
>   File "C:\Users\USER\Desktop\discord-log-bot-main\log-bot.py", line 1, in <module>
>     import discord
> ModuleNotFoundError: No module named 'discord'

I have discord.py installed correctly I believe.

**Comment by Isokok** [comment]
Retried after redownloading and following the same setup process.

C:\Users\USER\Desktop\discord-log-bot-main>python log-bot.py

> Traceback (most recent call last):
>   File "C:\Users\USER\Desktop\discord-log-bot-main\log-bot.py", line 1, in <module>
>     import discord
>   File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\__init__.py", line 20, in <module>
>     from .client import Client, AppInfo, ChannelPermissions
>   File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 38, in <module>
>     from .state import ConnectionState
>   File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\state.py", line 36, in <module>
>     from . import utils, compat
>   File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\compat.py", line 32
>     create_task = asyncio.async
>                           ^^^^^
> SyntaxError: invalid syntax

**Comment by kiwijuice56** [comment]
Sorry, my last advice was incorrect, this appears to be a python version issue! The current discord.py version seems to not work with python above version 3.6. Does following the advice at [this link](https://stackoverflow.com/questions/51196568/create-task-asyncio-async-syntaxerror-invalid-syntax) fix the problem?

**Comment by Isokok** [comment]
I uninstalled all but python 3.6 (I rarely use python) and this is what I got

C:\Users\USER\Desktop\discord-log-bot-main>python log-bot.py
> Traceback (most recent call last):
>   File "C:\Users\kale\Desktop\discord-log-bot-main\log-bot.py", line 1, in <module>
>     import discord
> ModuleNotFoundError: No module named 'discord'

So still no discord module. So, I reinstalled discord.py.

C:\Users\kale\Desktop\discord-log-bot-main>python log-bot.py
> Traceback (most recent call last):
>   File "C:\Users\USER\Desktop\discord-log-bot-main\log-bot.py", line 112, in <module>
>     bot.run(TOKEN)
>   File "C:\Users\USER\anaconda3\lib\site-packages\discord\client.py", line 723, in run
>     return future.result()
>   File "C:\Users\USER\anaconda3\lib\site-packages\discord\client.py", line 702, in runner
>     await self.start(*args, **kwargs)
>   File "C:\Users\USER\anaconda3\lib\site-packages\discord\client.py", line 666, in start
>     await self.connect(reconnect=reconnect)
>   File "C:\Users\USER\anaconda3\lib\site-packages\discord\client.py", line 601, in connect
>     raise PrivilegedIntentsRequired(exc.shard_id) from None
> discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
> Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002BACE0AE700>
> Traceback (most recent call last):
>   File "C:\Users\USER\anaconda3\lib\asyncio\proactor_events.py", line 116, in __del__
>     self.close()
>   File "C:\Users\USER\anaconda3\lib\asyncio\proactor_events.py", line 108, in close
>     self._loop.call_soon(self._call_connection_lost, None)
>   File "C:\Users\USER\anaconda3\lib\asyncio\base_events.py", line 746, in call_soon
>     self._check_closed()
>   File "C:\Users\USER\anaconda3\lib\asyncio\base_events.py", line 510, in _check_closed
>     raise RuntimeError('Event loop is closed')
> RuntimeError: Event loop is closed

So I fixed the problem with the bot acct settings and NOW IT WORKS.

Thank you so much for helping a dummy/newbie like me ❤️ 
Now got to reset up on the actual sever, thanks again.
